# Generated by Django 2.2.12 on 2020-05-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200507_0641'),
        ('users', '0002_auto_20200506_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nnbn',
            field=models.ManyToManyField(blank=True, related_name='user_nnbn', to='home.HomePage'),
        ),
    ]
