# Generated by Django 2.2.12 on 2020-05-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_load_initial_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtext",
            name="jghjg",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
