# Generated by Django 2.2.12 on 2020-05-06 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_customtext_jghjg"),
    ]

    operations = [
        migrations.RemoveField(model_name="customtext", name="jghjg",),
    ]
